export const LOGIN_LOAD = 'LOGIN_LOAD';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGIST_LOAD = 'REGIST_LOAD';
export const REGIST_SUCCESS = 'REGIST_SUCCESS';
export const REGIST_FAILED = 'REGIST_FAILED'

export const SIGNOUT_LOAD = 'SIGNOUT_LOAD';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILED = 'SIGNOUT_FAILED'

export const FORGOT_PASS_LOAD = 'FORGOT_PASS_LOAD';
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS';
export const FORGOT_PASS_FAILED = 'FORGOT_PASS_FAILED'

export const RESET_PASS_LOAD = 'RESET_PASS_LOAD';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FAILED = 'RESET_PASS_FAILED'


/** EMPLOYEE TYPE */
export const GET_EMPLOYEE_LOAD = 'GET_EMPLOYEE_LOAD';
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEE_FAILED = 'GET_EMPLOYEE_FAILED'

export const GET_EMPLOYEEID_LOAD = 'GET_EMPLOYEEID_LOAD';
export const GET_EMPLOYEEID_SUCCESS = 'GET_EMPLOYEEID_SUCCESS';
export const GET_EMPLOYEEID_FAILED = 'GET_EMPLOYEEID_FAILED'

export const ADD_EMPLOYEE_LOAD = 'ADD_EMPLOYEE_LOAD';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILED = 'ADD_EMPLOYEE_FAILED'
 
export const EDIT_EMPLOYEE_LOAD = 'EDIT_EMPLOYEE_LOAD';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_FAILED = 'EDIT_EMPLOYEE_FAILED'
 
export const DELETE_EMPLOYEE_LOAD = 'DELETE_EMPLOYEE_LOAD';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILED = 'DELETE_EMPLOYEE_FAILED'
 

/** PRODUCT TYPE */
export const GET_PRODUCT_LOAD = 'GET_PRODUCT_LOAD';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED'

export const GET_PRODUCTID_LOAD = 'GET_PRODUCTID_LOAD';
export const GET_PRODUCTID_SUCCESS = 'GET_PRODUCTID_SUCCESS';
export const GET_PRODUCTID_FAILED = 'GET_PRODUCTID_FAILED'

export const ADD_PRODUCT_LOAD = 'ADD_PRODUCT_LOAD';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED'
 
export const EDIT_PRODUCT_LOAD = 'EDIT_PRODUCT_LOAD';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_FAILED = 'EDIT_PRODUCT_FAILED'
 
export const DELETE_PRODUCT_LOAD = 'DELETE_PRODUCT_LOAD';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED'
 