export const LOGIN_LOAD = 'LOGIN_LOAD';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGIST_LOAD = 'REGIST_LOAD';
export const REGIST_SUCCESS = 'REGIST_SUCCESS';
export const REGIST_FAILED = 'REGIST_FAILED'

export const SIGNOUT_LOAD = 'SIGNOUT_LOAD';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILED = 'SIGNOUT_FAILED'

export const FORGOT_PASS_LOAD = 'FORGOT_PASS_LOAD';
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS';
export const FORGOT_PASS_FAILED = 'FORGOT_PASS_FAILED'

export const RESET_PASS_LOAD = 'RESET_PASS_LOAD';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FAILED = 'RESET_PASS_FAILED'